/*
  Warnings:

  - Added the required column `entity` to the `AuditLog` table without a default value. This is not possible if the table is not empty.

*/
-- AlterTable
ALTER TABLE `auditlog` ADD COLUMN `entity` VARCHAR(191) NOT NULL,
    ADD COLUMN `entityId` INTEGER NULL,
    ADD COLUMN `ipAddress` VARCHAR(191) NULL,
    ADD COLUMN `userAgent` TEXT NULL,
    MODIFY `action` ENUM('USER_LOGIN', 'USER_LOGOUT', 'USER_LOGIN_FAILED', 'LDAP_LOGIN', 'PASSWORD_CHANGED', 'ROLE_ASSIGNED', 'ROLE_REMOVED', 'REQUEST_CREATED', 'REQUEST_UPDATED', 'REQUEST_DELETED', 'REQUEST_SUBMITTED', 'REQUEST_APPROVED', 'REQUEST_REJECTED', 'REQUEST_FORWARDED', 'REQUEST_RETURNED', 'REQUEST_STATUS_CHANGED', 'PO_CREATED', 'PO_UPDATED', 'PO_APPROVED', 'PO_CANCELLED', 'APPROVAL_GRANTED', 'APPROVAL_DENIED', 'APPROVAL_DELEGATED', 'WORKFLOW_STAGE_CHANGED', 'BUDGET_ALLOCATED', 'BUDGET_MODIFIED', 'PAYMENT_PROCESSED', 'FILE_UPLOADED', 'FILE_DOWNLOADED', 'FILE_DELETED', 'IDEA_CREATED', 'IDEA_UPDATED', 'IDEA_VOTED', 'IDEA_DELETED', 'COMMENT_CREATED', 'COMMENT_DELETED', 'STAGE_CHANGED', 'TAGS_UPDATED', 'SUPPLIER_CREATED', 'SUPPLIER_UPDATED', 'SUPPLIER_APPROVED', 'SUPPLIER_SUSPENDED', 'USER_CREATED', 'USER_UPDATED', 'USER_DELETED', 'SETTINGS_CHANGED', 'REPORT_GENERATED', 'DATA_EXPORTED') NOT NULL,
    MODIFY `message` TEXT NOT NULL;

-- AlterTable
ALTER TABLE `user` ADD COLUMN `profileImage` VARCHAR(191) NULL;

-- CreateIndex
CREATE INDEX `AuditLog_action_idx` ON `AuditLog`(`action`);

-- CreateIndex
CREATE INDEX `AuditLog_entity_entityId_idx` ON `AuditLog`(`entity`, `entityId`);

-- CreateIndex
CREATE INDEX `AuditLog_createdAt_idx` ON `AuditLog`(`createdAt`);
