-- AlterTable
ALTER TABLE `notification` MODIFY `type` ENUM('MENTION', 'STAGE_CHANGED', 'IDEA_APPROVED', 'THRESHOLD_EXCEEDED') NOT NULL;

-- AlterTable
ALTER TABLE `request` MODIFY `status` ENUM('DRAFT', 'SUBMITTED', 'DEPARTMENT_REVIEW', 'DEPARTMENT_RETURNED', 'DEPARTMENT_APPROVED', 'EXECUTIVE_REVIEW', 'HOD_REVIEW', 'PROCUREMENT_REVIEW', 'FINANCE_REVIEW', 'FINANCE_RETURNED', 'BUDGET_MANAGER_REVIEW', 'FINANCE_APPROVED', 'SENT_TO_VENDOR', 'CLOSED', 'REJECTED') NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE `requeststatushistory` MODIFY `status` ENUM('DRAFT', 'SUBMITTED', 'DEPARTMENT_REVIEW', 'DEPARTMENT_RETURNED', 'DEPARTMENT_APPROVED', 'EXECUTIVE_REVIEW', 'HOD_REVIEW', 'PROCUREMENT_REVIEW', 'FINANCE_REVIEW', 'FINANCE_RETURNED', 'BUDGET_MANAGER_REVIEW', 'FINANCE_APPROVED', 'SENT_TO_VENDOR', 'CLOSED', 'REJECTED') NOT NULL;
